// This file is autogenerated. Take a look at `Preprocessor` target in RxSwift project 
//
//  CombineLatest+arity.swift
//  RxSwift
//
//  Created by Krunoslav Zaher on 4/22/15.
//  Copyright © 2015 Krunoslav Zaher. All rights reserved.
//



// 2

extension _RXSwift_ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2, resultSelector: @escaping (O1.Element, O2.Element) throws -> Element)
            -> _RXSwift_Observable<Element> {
        return _RXSwift_CombineLatest2(
            source1: source1.asObservable(), source2: source2.asObservable(),
            resultSelector: resultSelector
        )
    }
}

extension _RXSwift_ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2)
            -> _RXSwift_Observable<(O1.Element, O2.Element)> {
        return _RXSwift_CombineLatest2(
            source1: source1.asObservable(), source2: source2.asObservable(),
            resultSelector: { ($0, $1) }
        )
    }
}

final class _RXSwift_CombineLatestSink2_<E1, E2, Observer: _RXSwift_ObserverType> : _RXSwift_CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = _RXSwift_CombineLatest2<E1, E2, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil

    init(parent: Parent, observer: Observer, cancel: _RXSwift_Cancelable) {
        self._parent = parent
        super.init(arity: 2, observer: observer, cancel: cancel)
    }

    func run() -> _RXSwift_Disposable {
        let subscription1 = _RXSwift_SingleAssignmentDisposable()
        let subscription2 = _RXSwift_SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)

         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))

        return _RXSwift_Disposables.create([
                subscription1,
                subscription2
        ])
    }

    override func getResult() throws-> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2)
    }
}

final class _RXSwift_CombineLatest2<E1, E2, Result> : _RXSwift_Producer<Result> {
    typealias ResultSelector = (E1, E2) throws -> Result

    let _source1: _RXSwift_Observable<E1>
    let _source2: _RXSwift_Observable<E2>

    let _resultSelector: ResultSelector

    init(source1: _RXSwift_Observable<E1>, source2: _RXSwift_Observable<E2>, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2

        self._resultSelector = resultSelector
    }

    override func run<Observer: _RXSwift_ObserverType>(_ observer: Observer, cancel: _RXSwift_Cancelable) -> (sink: _RXSwift_Disposable, subscription: _RXSwift_Disposable) where Observer.Element == Result {
        let sink = _RXSwift_CombineLatestSink2_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run()
        return (sink: sink, subscription: subscription)
    }
}



// 3

extension _RXSwift_ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType, O3: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, resultSelector: @escaping (O1.Element, O2.Element, O3.Element) throws -> Element)
            -> _RXSwift_Observable<Element> {
        return _RXSwift_CombineLatest3(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(),
            resultSelector: resultSelector
        )
    }
}

extension _RXSwift_ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType, O3: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3)
            -> _RXSwift_Observable<(O1.Element, O2.Element, O3.Element)> {
        return _RXSwift_CombineLatest3(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(),
            resultSelector: { ($0, $1, $2) }
        )
    }
}

final class _RXSwift_CombineLatestSink3_<E1, E2, E3, Observer: _RXSwift_ObserverType> : _RXSwift_CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = _RXSwift_CombineLatest3<E1, E2, E3, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil
    var _latestElement3: E3! = nil

    init(parent: Parent, observer: Observer, cancel: _RXSwift_Cancelable) {
        self._parent = parent
        super.init(arity: 3, observer: observer, cancel: cancel)
    }

    func run() -> _RXSwift_Disposable {
        let subscription1 = _RXSwift_SingleAssignmentDisposable()
        let subscription2 = _RXSwift_SingleAssignmentDisposable()
        let subscription3 = _RXSwift_SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)
        let observer3 = CombineLatestObserver(lock: self._lock, parent: self, index: 2, setLatestValue: { (e: E3) -> Void in self._latestElement3 = e }, this: subscription3)

         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))
         subscription3.setDisposable(self._parent._source3.subscribe(observer3))

        return _RXSwift_Disposables.create([
                subscription1,
                subscription2,
                subscription3
        ])
    }

    override func getResult() throws-> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2, self._latestElement3)
    }
}

final class _RXSwift_CombineLatest3<E1, E2, E3, Result> : _RXSwift_Producer<Result> {
    typealias ResultSelector = (E1, E2, E3) throws-> Result

    let _source1: _RXSwift_Observable<E1>
    let _source2: _RXSwift_Observable<E2>
    let _source3: _RXSwift_Observable<E3>

    let _resultSelector: ResultSelector

    init(source1: _RXSwift_Observable<E1>, source2: _RXSwift_Observable<E2>, source3: _RXSwift_Observable<E3>, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2
        self._source3 = source3

        self._resultSelector = resultSelector
    }

    override func run<Observer: _RXSwift_ObserverType>(_ observer: Observer, cancel: _RXSwift_Cancelable) -> (sink: _RXSwift_Disposable, subscription: _RXSwift_Disposable) where Observer.Element == Result {
        let sink = _RXSwift_CombineLatestSink3_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run()
        return (sink: sink, subscription: subscription)
    }
}



// 4

extension _RXSwift_ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType, O3: _RXSwift_ObservableType, O4: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, resultSelector: @escaping (O1.Element, O2.Element, O3.Element, O4.Element) throws -> Element)
            -> _RXSwift_Observable<Element> {
        return _RXSwift_CombineLatest4(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(),
            resultSelector: resultSelector
        )
    }
}

extension _RXSwift_ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType, O3: _RXSwift_ObservableType, O4: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4)
            -> _RXSwift_Observable<(O1.Element, O2.Element, O3.Element, O4.Element)> {
        return _RXSwift_CombineLatest4(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(),
            resultSelector: { ($0, $1, $2, $3) }
        )
    }
}

final class _RXSwift_CombineLatestSink4_<E1, E2, E3, E4, Observer: _RXSwift_ObserverType> : _RXSwift_CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = _RXSwift_CombineLatest4<E1, E2, E3, E4, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil
    var _latestElement3: E3! = nil
    var _latestElement4: E4! = nil

    init(parent: Parent, observer: Observer, cancel: _RXSwift_Cancelable) {
        self._parent = parent
        super.init(arity: 4, observer: observer, cancel: cancel)
    }

    func run() -> _RXSwift_Disposable {
        let subscription1 = _RXSwift_SingleAssignmentDisposable()
        let subscription2 = _RXSwift_SingleAssignmentDisposable()
        let subscription3 = _RXSwift_SingleAssignmentDisposable()
        let subscription4 = _RXSwift_SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)
        let observer3 = CombineLatestObserver(lock: self._lock, parent: self, index: 2, setLatestValue: { (e: E3) -> Void in self._latestElement3 = e }, this: subscription3)
        let observer4 = CombineLatestObserver(lock: self._lock, parent: self, index: 3, setLatestValue: { (e: E4) -> Void in self._latestElement4 = e }, this: subscription4)

         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))
         subscription3.setDisposable(self._parent._source3.subscribe(observer3))
         subscription4.setDisposable(self._parent._source4.subscribe(observer4))

        return _RXSwift_Disposables.create([
                subscription1,
                subscription2,
                subscription3,
                subscription4
        ])
    }

    override func getResult() throws-> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2, self._latestElement3, self._latestElement4)
    }
}

final class _RXSwift_CombineLatest4<E1, E2, E3, E4, Result> : _RXSwift_Producer<Result> {
    typealias ResultSelector = (E1, E2, E3, E4) throws-> Result

    let _source1: _RXSwift_Observable<E1>
    let _source2: _RXSwift_Observable<E2>
    let _source3: _RXSwift_Observable<E3>
    let _source4: _RXSwift_Observable<E4>

    let _resultSelector: ResultSelector

    init(source1: _RXSwift_Observable<E1>, source2: _RXSwift_Observable<E2>, source3: _RXSwift_Observable<E3>, source4: _RXSwift_Observable<E4>, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2
        self._source3 = source3
        self._source4 = source4

        self._resultSelector = resultSelector
    }

    override func run<Observer: _RXSwift_ObserverType>(_ observer: Observer, cancel: _RXSwift_Cancelable) -> (sink: _RXSwift_Disposable, subscription: _RXSwift_Disposable) where Observer.Element == Result {
        let sink = _RXSwift_CombineLatestSink4_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run()
        return (sink: sink, subscription: subscription)
    }
}



// 5

extension _RXSwift_ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType, O3: _RXSwift_ObservableType, O4: _RXSwift_ObservableType, O5: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, resultSelector: @escaping (O1.Element, O2.Element, O3.Element, O4.Element, O5.Element) throws -> Element)
            -> _RXSwift_Observable<Element> {
        return _RXSwift_CombineLatest5(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(),
            resultSelector: resultSelector
        )
    }
}

extension _RXSwift_ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType, O3: _RXSwift_ObservableType, O4: _RXSwift_ObservableType, O5: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5)
            -> _RXSwift_Observable<(O1.Element, O2.Element, O3.Element, O4.Element, O5.Element)> {
        return _RXSwift_CombineLatest5(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(),
            resultSelector: { ($0, $1, $2, $3, $4) }
        )
    }
}

final class _RXSwift_CombineLatestSink5_<E1, E2, E3, E4, E5, Observer: _RXSwift_ObserverType> : _RXSwift_CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = _RXSwift_CombineLatest5<E1, E2, E3, E4, E5, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil
    var _latestElement3: E3! = nil
    var _latestElement4: E4! = nil
    var _latestElement5: E5! = nil

    init(parent: Parent, observer: Observer, cancel: _RXSwift_Cancelable) {
        self._parent = parent
        super.init(arity: 5, observer: observer, cancel: cancel)
    }

    func run() -> _RXSwift_Disposable {
        let subscription1 = _RXSwift_SingleAssignmentDisposable()
        let subscription2 = _RXSwift_SingleAssignmentDisposable()
        let subscription3 = _RXSwift_SingleAssignmentDisposable()
        let subscription4 = _RXSwift_SingleAssignmentDisposable()
        let subscription5 = _RXSwift_SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)
        let observer3 = CombineLatestObserver(lock: self._lock, parent: self, index: 2, setLatestValue: { (e: E3) -> Void in self._latestElement3 = e }, this: subscription3)
        let observer4 = CombineLatestObserver(lock: self._lock, parent: self, index: 3, setLatestValue: { (e: E4) -> Void in self._latestElement4 = e }, this: subscription4)
        let observer5 = CombineLatestObserver(lock: self._lock, parent: self, index: 4, setLatestValue: { (e: E5) -> Void in self._latestElement5 = e }, this: subscription5)

         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))
         subscription3.setDisposable(self._parent._source3.subscribe(observer3))
         subscription4.setDisposable(self._parent._source4.subscribe(observer4))
         subscription5.setDisposable(self._parent._source5.subscribe(observer5))

        return _RXSwift_Disposables.create([
                subscription1,
                subscription2,
                subscription3,
                subscription4,
                subscription5
        ])
    }

    override func getResult() throws-> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2, self._latestElement3, self._latestElement4, self._latestElement5)
    }
}

final class _RXSwift_CombineLatest5<E1, E2, E3, E4, E5, Result> : _RXSwift_Producer<Result> {
    typealias ResultSelector = (E1, E2, E3, E4, E5) throws-> Result

    let _source1: _RXSwift_Observable<E1>
    let _source2: _RXSwift_Observable<E2>
    let _source3: _RXSwift_Observable<E3>
    let _source4: _RXSwift_Observable<E4>
    let _source5: _RXSwift_Observable<E5>

    let _resultSelector: ResultSelector

    init(source1: _RXSwift_Observable<E1>, source2: _RXSwift_Observable<E2>, source3: _RXSwift_Observable<E3>, source4: _RXSwift_Observable<E4>, source5: _RXSwift_Observable<E5>, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2
        self._source3 = source3
        self._source4 = source4
        self._source5 = source5

        self._resultSelector = resultSelector
    }

    override func run<Observer: _RXSwift_ObserverType>(_ observer: Observer, cancel: _RXSwift_Cancelable) -> (sink: _RXSwift_Disposable, subscription: _RXSwift_Disposable) where Observer.Element == Result {
        let sink = _RXSwift_CombineLatestSink5_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run()
        return (sink: sink, subscription: subscription)
    }
}



// 6

extension _RXSwift_ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType, O3: _RXSwift_ObservableType, O4: _RXSwift_ObservableType, O5: _RXSwift_ObservableType, O6: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, _ source6: O6, resultSelector: @escaping (O1.Element, O2.Element, O3.Element, O4.Element, O5.Element, O6.Element) throws -> Element)
            -> _RXSwift_Observable<Element> {
        return _RXSwift_CombineLatest6(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(), source6: source6.asObservable(),
            resultSelector: resultSelector
        )
    }
}

extension _RXSwift_ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType, O3: _RXSwift_ObservableType, O4: _RXSwift_ObservableType, O5: _RXSwift_ObservableType, O6: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, _ source6: O6)
            -> _RXSwift_Observable<(O1.Element, O2.Element, O3.Element, O4.Element, O5.Element, O6.Element)> {
        return _RXSwift_CombineLatest6(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(), source6: source6.asObservable(),
            resultSelector: { ($0, $1, $2, $3, $4, $5) }
        )
    }
}

final class _RXSwift_CombineLatestSink6_<E1, E2, E3, E4, E5, E6, Observer: _RXSwift_ObserverType> : _RXSwift_CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = _RXSwift_CombineLatest6<E1, E2, E3, E4, E5, E6, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil
    var _latestElement3: E3! = nil
    var _latestElement4: E4! = nil
    var _latestElement5: E5! = nil
    var _latestElement6: E6! = nil

    init(parent: Parent, observer: Observer, cancel: _RXSwift_Cancelable) {
        self._parent = parent
        super.init(arity: 6, observer: observer, cancel: cancel)
    }

    func run() -> _RXSwift_Disposable {
        let subscription1 = _RXSwift_SingleAssignmentDisposable()
        let subscription2 = _RXSwift_SingleAssignmentDisposable()
        let subscription3 = _RXSwift_SingleAssignmentDisposable()
        let subscription4 = _RXSwift_SingleAssignmentDisposable()
        let subscription5 = _RXSwift_SingleAssignmentDisposable()
        let subscription6 = _RXSwift_SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)
        let observer3 = CombineLatestObserver(lock: self._lock, parent: self, index: 2, setLatestValue: { (e: E3) -> Void in self._latestElement3 = e }, this: subscription3)
        let observer4 = CombineLatestObserver(lock: self._lock, parent: self, index: 3, setLatestValue: { (e: E4) -> Void in self._latestElement4 = e }, this: subscription4)
        let observer5 = CombineLatestObserver(lock: self._lock, parent: self, index: 4, setLatestValue: { (e: E5) -> Void in self._latestElement5 = e }, this: subscription5)
        let observer6 = CombineLatestObserver(lock: self._lock, parent: self, index: 5, setLatestValue: { (e: E6) -> Void in self._latestElement6 = e }, this: subscription6)

         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))
         subscription3.setDisposable(self._parent._source3.subscribe(observer3))
         subscription4.setDisposable(self._parent._source4.subscribe(observer4))
         subscription5.setDisposable(self._parent._source5.subscribe(observer5))
         subscription6.setDisposable(self._parent._source6.subscribe(observer6))

        return _RXSwift_Disposables.create([
                subscription1,
                subscription2,
                subscription3,
                subscription4,
                subscription5,
                subscription6
        ])
    }

    override func getResult() throws-> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2, self._latestElement3, self._latestElement4, self._latestElement5, self._latestElement6)
    }
}

final class _RXSwift_CombineLatest6<E1, E2, E3, E4, E5, E6, Result> : _RXSwift_Producer<Result> {
    typealias ResultSelector = (E1, E2, E3, E4, E5, E6) throws-> Result

    let _source1: _RXSwift_Observable<E1>
    let _source2: _RXSwift_Observable<E2>
    let _source3: _RXSwift_Observable<E3>
    let _source4: _RXSwift_Observable<E4>
    let _source5: _RXSwift_Observable<E5>
    let _source6: _RXSwift_Observable<E6>

    let _resultSelector: ResultSelector

    init(source1: _RXSwift_Observable<E1>, source2: _RXSwift_Observable<E2>, source3: _RXSwift_Observable<E3>, source4: _RXSwift_Observable<E4>, source5: _RXSwift_Observable<E5>, source6: _RXSwift_Observable<E6>, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2
        self._source3 = source3
        self._source4 = source4
        self._source5 = source5
        self._source6 = source6

        self._resultSelector = resultSelector
    }

    override func run<Observer: _RXSwift_ObserverType>(_ observer: Observer, cancel: _RXSwift_Cancelable) -> (sink: _RXSwift_Disposable, subscription: _RXSwift_Disposable) where Observer.Element == Result {
        let sink = _RXSwift_CombineLatestSink6_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run()
        return (sink: sink, subscription: subscription)
    }
}



// 7

extension _RXSwift_ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType, O3: _RXSwift_ObservableType, O4: _RXSwift_ObservableType, O5: _RXSwift_ObservableType, O6: _RXSwift_ObservableType, O7: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, _ source6: O6, _ source7: O7, resultSelector: @escaping (O1.Element, O2.Element, O3.Element, O4.Element, O5.Element, O6.Element, O7.Element) throws -> Element)
            -> _RXSwift_Observable<Element> {
        return _RXSwift_CombineLatest7(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(), source6: source6.asObservable(), source7: source7.asObservable(),
            resultSelector: resultSelector
        )
    }
}

extension _RXSwift_ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType, O3: _RXSwift_ObservableType, O4: _RXSwift_ObservableType, O5: _RXSwift_ObservableType, O6: _RXSwift_ObservableType, O7: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, _ source6: O6, _ source7: O7)
            -> _RXSwift_Observable<(O1.Element, O2.Element, O3.Element, O4.Element, O5.Element, O6.Element, O7.Element)> {
        return _RXSwift_CombineLatest7(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(), source6: source6.asObservable(), source7: source7.asObservable(),
            resultSelector: { ($0, $1, $2, $3, $4, $5, $6) }
        )
    }
}

final class _RXSwift_CombineLatestSink7_<E1, E2, E3, E4, E5, E6, E7, Observer: _RXSwift_ObserverType> : _RXSwift_CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = _RXSwift_CombineLatest7<E1, E2, E3, E4, E5, E6, E7, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil
    var _latestElement3: E3! = nil
    var _latestElement4: E4! = nil
    var _latestElement5: E5! = nil
    var _latestElement6: E6! = nil
    var _latestElement7: E7! = nil

    init(parent: Parent, observer: Observer, cancel: _RXSwift_Cancelable) {
        self._parent = parent
        super.init(arity: 7, observer: observer, cancel: cancel)
    }

    func run() -> _RXSwift_Disposable {
        let subscription1 = _RXSwift_SingleAssignmentDisposable()
        let subscription2 = _RXSwift_SingleAssignmentDisposable()
        let subscription3 = _RXSwift_SingleAssignmentDisposable()
        let subscription4 = _RXSwift_SingleAssignmentDisposable()
        let subscription5 = _RXSwift_SingleAssignmentDisposable()
        let subscription6 = _RXSwift_SingleAssignmentDisposable()
        let subscription7 = _RXSwift_SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)
        let observer3 = CombineLatestObserver(lock: self._lock, parent: self, index: 2, setLatestValue: { (e: E3) -> Void in self._latestElement3 = e }, this: subscription3)
        let observer4 = CombineLatestObserver(lock: self._lock, parent: self, index: 3, setLatestValue: { (e: E4) -> Void in self._latestElement4 = e }, this: subscription4)
        let observer5 = CombineLatestObserver(lock: self._lock, parent: self, index: 4, setLatestValue: { (e: E5) -> Void in self._latestElement5 = e }, this: subscription5)
        let observer6 = CombineLatestObserver(lock: self._lock, parent: self, index: 5, setLatestValue: { (e: E6) -> Void in self._latestElement6 = e }, this: subscription6)
        let observer7 = CombineLatestObserver(lock: self._lock, parent: self, index: 6, setLatestValue: { (e: E7) -> Void in self._latestElement7 = e }, this: subscription7)

         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))
         subscription3.setDisposable(self._parent._source3.subscribe(observer3))
         subscription4.setDisposable(self._parent._source4.subscribe(observer4))
         subscription5.setDisposable(self._parent._source5.subscribe(observer5))
         subscription6.setDisposable(self._parent._source6.subscribe(observer6))
         subscription7.setDisposable(self._parent._source7.subscribe(observer7))

        return _RXSwift_Disposables.create([
                subscription1,
                subscription2,
                subscription3,
                subscription4,
                subscription5,
                subscription6,
                subscription7
        ])
    }

    override func getResult() throws-> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2, self._latestElement3, self._latestElement4, self._latestElement5, self._latestElement6, self._latestElement7)
    }
}

final class _RXSwift_CombineLatest7<E1, E2, E3, E4, E5, E6, E7, Result> : _RXSwift_Producer<Result> {
    typealias ResultSelector = (E1, E2, E3, E4, E5, E6, E7) throws-> Result

    let _source1: _RXSwift_Observable<E1>
    let _source2: _RXSwift_Observable<E2>
    let _source3: _RXSwift_Observable<E3>
    let _source4: _RXSwift_Observable<E4>
    let _source5: _RXSwift_Observable<E5>
    let _source6: _RXSwift_Observable<E6>
    let _source7: _RXSwift_Observable<E7>

    let _resultSelector: ResultSelector

    init(source1: _RXSwift_Observable<E1>, source2: _RXSwift_Observable<E2>, source3: _RXSwift_Observable<E3>, source4: _RXSwift_Observable<E4>, source5: _RXSwift_Observable<E5>, source6: _RXSwift_Observable<E6>, source7: _RXSwift_Observable<E7>, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2
        self._source3 = source3
        self._source4 = source4
        self._source5 = source5
        self._source6 = source6
        self._source7 = source7

        self._resultSelector = resultSelector
    }

    override func run<Observer: _RXSwift_ObserverType>(_ observer: Observer, cancel: _RXSwift_Cancelable) -> (sink: _RXSwift_Disposable, subscription: _RXSwift_Disposable) where Observer.Element == Result {
        let sink = _RXSwift_CombineLatestSink7_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run()
        return (sink: sink, subscription: subscription)
    }
}



// 8

extension _RXSwift_ObservableType {
    /**
    Merges the specified observable sequences into one observable sequence by using the selector function whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - parameter resultSelector: Function to invoke whenever any of the sources produces an element.
    - returns: An observable sequence containing the result of combining elements of the sources using the specified result selector function.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType, O3: _RXSwift_ObservableType, O4: _RXSwift_ObservableType, O5: _RXSwift_ObservableType, O6: _RXSwift_ObservableType, O7: _RXSwift_ObservableType, O8: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, _ source6: O6, _ source7: O7, _ source8: O8, resultSelector: @escaping (O1.Element, O2.Element, O3.Element, O4.Element, O5.Element, O6.Element, O7.Element, O8.Element) throws -> Element)
            -> _RXSwift_Observable<Element> {
        return _RXSwift_CombineLatest8(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(), source6: source6.asObservable(), source7: source7.asObservable(), source8: source8.asObservable(),
            resultSelector: resultSelector
        )
    }
}

extension _RXSwift_ObservableType where Element == Any {
    /**
    Merges the specified observable sequences into one observable sequence of tuples whenever any of the observable sequences produces an element.

    - seealso: [combineLatest operator on reactivex.io](http://reactivex.io/documentation/operators/combinelatest.html)

    - returns: An observable sequence containing the result of combining elements of the sources.
    */
    static func combineLatest<O1: _RXSwift_ObservableType, O2: _RXSwift_ObservableType, O3: _RXSwift_ObservableType, O4: _RXSwift_ObservableType, O5: _RXSwift_ObservableType, O6: _RXSwift_ObservableType, O7: _RXSwift_ObservableType, O8: _RXSwift_ObservableType>
        (_ source1: O1, _ source2: O2, _ source3: O3, _ source4: O4, _ source5: O5, _ source6: O6, _ source7: O7, _ source8: O8)
            -> _RXSwift_Observable<(O1.Element, O2.Element, O3.Element, O4.Element, O5.Element, O6.Element, O7.Element, O8.Element)> {
        return _RXSwift_CombineLatest8(
            source1: source1.asObservable(), source2: source2.asObservable(), source3: source3.asObservable(), source4: source4.asObservable(), source5: source5.asObservable(), source6: source6.asObservable(), source7: source7.asObservable(), source8: source8.asObservable(),
            resultSelector: { ($0, $1, $2, $3, $4, $5, $6, $7) }
        )
    }
}

final class _RXSwift_CombineLatestSink8_<E1, E2, E3, E4, E5, E6, E7, E8, Observer: _RXSwift_ObserverType> : _RXSwift_CombineLatestSink<Observer> {
    typealias Result = Observer.Element
    typealias Parent = _RXSwift_CombineLatest8<E1, E2, E3, E4, E5, E6, E7, E8, Result>

    let _parent: Parent

    var _latestElement1: E1! = nil
    var _latestElement2: E2! = nil
    var _latestElement3: E3! = nil
    var _latestElement4: E4! = nil
    var _latestElement5: E5! = nil
    var _latestElement6: E6! = nil
    var _latestElement7: E7! = nil
    var _latestElement8: E8! = nil

    init(parent: Parent, observer: Observer, cancel: _RXSwift_Cancelable) {
        self._parent = parent
        super.init(arity: 8, observer: observer, cancel: cancel)
    }

    func run() -> _RXSwift_Disposable {
        let subscription1 = _RXSwift_SingleAssignmentDisposable()
        let subscription2 = _RXSwift_SingleAssignmentDisposable()
        let subscription3 = _RXSwift_SingleAssignmentDisposable()
        let subscription4 = _RXSwift_SingleAssignmentDisposable()
        let subscription5 = _RXSwift_SingleAssignmentDisposable()
        let subscription6 = _RXSwift_SingleAssignmentDisposable()
        let subscription7 = _RXSwift_SingleAssignmentDisposable()
        let subscription8 = _RXSwift_SingleAssignmentDisposable()

        let observer1 = CombineLatestObserver(lock: self._lock, parent: self, index: 0, setLatestValue: { (e: E1) -> Void in self._latestElement1 = e }, this: subscription1)
        let observer2 = CombineLatestObserver(lock: self._lock, parent: self, index: 1, setLatestValue: { (e: E2) -> Void in self._latestElement2 = e }, this: subscription2)
        let observer3 = CombineLatestObserver(lock: self._lock, parent: self, index: 2, setLatestValue: { (e: E3) -> Void in self._latestElement3 = e }, this: subscription3)
        let observer4 = CombineLatestObserver(lock: self._lock, parent: self, index: 3, setLatestValue: { (e: E4) -> Void in self._latestElement4 = e }, this: subscription4)
        let observer5 = CombineLatestObserver(lock: self._lock, parent: self, index: 4, setLatestValue: { (e: E5) -> Void in self._latestElement5 = e }, this: subscription5)
        let observer6 = CombineLatestObserver(lock: self._lock, parent: self, index: 5, setLatestValue: { (e: E6) -> Void in self._latestElement6 = e }, this: subscription6)
        let observer7 = CombineLatestObserver(lock: self._lock, parent: self, index: 6, setLatestValue: { (e: E7) -> Void in self._latestElement7 = e }, this: subscription7)
        let observer8 = CombineLatestObserver(lock: self._lock, parent: self, index: 7, setLatestValue: { (e: E8) -> Void in self._latestElement8 = e }, this: subscription8)

         subscription1.setDisposable(self._parent._source1.subscribe(observer1))
         subscription2.setDisposable(self._parent._source2.subscribe(observer2))
         subscription3.setDisposable(self._parent._source3.subscribe(observer3))
         subscription4.setDisposable(self._parent._source4.subscribe(observer4))
         subscription5.setDisposable(self._parent._source5.subscribe(observer5))
         subscription6.setDisposable(self._parent._source6.subscribe(observer6))
         subscription7.setDisposable(self._parent._source7.subscribe(observer7))
         subscription8.setDisposable(self._parent._source8.subscribe(observer8))

        return _RXSwift_Disposables.create([
                subscription1,
                subscription2,
                subscription3,
                subscription4,
                subscription5,
                subscription6,
                subscription7,
                subscription8
        ])
    }

    override func getResult() throws-> Result {
        return try self._parent._resultSelector(self._latestElement1, self._latestElement2, self._latestElement3, self._latestElement4, self._latestElement5, self._latestElement6, self._latestElement7, self._latestElement8)
    }
}

final class _RXSwift_CombineLatest8<E1, E2, E3, E4, E5, E6, E7, E8, Result> : _RXSwift_Producer<Result> {
    typealias ResultSelector = (E1, E2, E3, E4, E5, E6, E7, E8) throws-> Result

    let _source1: _RXSwift_Observable<E1>
    let _source2: _RXSwift_Observable<E2>
    let _source3: _RXSwift_Observable<E3>
    let _source4: _RXSwift_Observable<E4>
    let _source5: _RXSwift_Observable<E5>
    let _source6: _RXSwift_Observable<E6>
    let _source7: _RXSwift_Observable<E7>
    let _source8: _RXSwift_Observable<E8>

    let _resultSelector: ResultSelector

    init(source1: _RXSwift_Observable<E1>, source2: _RXSwift_Observable<E2>, source3: _RXSwift_Observable<E3>, source4: _RXSwift_Observable<E4>, source5: _RXSwift_Observable<E5>, source6: _RXSwift_Observable<E6>, source7: _RXSwift_Observable<E7>, source8: _RXSwift_Observable<E8>, resultSelector: @escaping ResultSelector) {
        self._source1 = source1
        self._source2 = source2
        self._source3 = source3
        self._source4 = source4
        self._source5 = source5
        self._source6 = source6
        self._source7 = source7
        self._source8 = source8

        self._resultSelector = resultSelector
    }

    override func run<Observer: _RXSwift_ObserverType>(_ observer: Observer, cancel: _RXSwift_Cancelable) -> (sink: _RXSwift_Disposable, subscription: _RXSwift_Disposable) where Observer.Element == Result {
        let sink = _RXSwift_CombineLatestSink8_(parent: self, observer: observer, cancel: cancel)
        let subscription = sink.run()
        return (sink: sink, subscription: subscription)
    }
}


